### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by manojps** [AtomLinter/linter-gcc#213] opened 2019-12-24 21:07 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /Users/msaha/.atom/packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
  4x -9:58.8.0 core:save (input.hidden-input)
  3x -9:55.6.0 core:backspace (input.hidden-input)
  8x -9:52.2.0 core:save (input.hidden-input)
  2x -8:44.7.0 core:backspace (input.hidden-input)
  7x -8:41.1.0 core:save (input.hidden-input)
     -8:34.8.0 core:backspace (input.hidden-input)
  7x -8:33.4.0 core:save (input.hidden-input)
     -8:06.5.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
  4x -1:33.3.0 core:backspace (input.hidden-input)
     -0:41.2.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -0:36.5.0 grammar-selector:show (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-beautify undefined 
linter-gcc 0.7.1 
script 3.25.0 
```

**Comment by Arcanemagus** [comment] 2019-12-27 19:54
Duplicate of #209

**Closed by Arcanemagus** 2019-12-27 19:54 UTC
Labels: duplicate
