### ISSUE TITLE
The linter-gcc does not point out my errors.

### ISSUE THREAD

**Issue by Lavenderloved** [AtomLinter/linter-gcc#197] opened 2018-12-11 18:14 UTC
There is a obvious error in the line 4,but there are no tips showing that I am wrong.
![image](https://user-images.githubusercontent.com/43584198/49820660-7c3ac600-fdb3-11e8-9ea2-80f5fa1eb082.png)

**Comment by Otavva** [comment] 2019-01-13 20:02
I have this issue too!

**Comment by SpeedrunnerG55** [comment] 2019-01-14 20:49
#199 Check if you are using linter 2.3.0, the last update removed support for the old linter API and this package uses it

**Comment by Otavva** [comment] 2019-01-16 17:31
Oh! Thank you so much! At now I can use it!

**Comment by Arcanemagus** [comment] 2019-01-16 18:13
@Otavva it's highly likely you are hitting https://github.com/hebaishi/linter-gcc/issues/199.

**Comment by otbrown** [comment] 2019-02-06 15:03
As it seems linter-gcc is no longer maintained @tvincent056 has published his fork which is compatible with the updated base linter as [linter-gcc2](https://atom.io/packages/linter-gcc2). See [comment](https://github.com/hebaishi/linter-gcc/pull/185#issuecomment-435928445) on #185

**Comment by Arcanemagus** [comment] 2019-12-23 20:12
Duplicate of #199

**Closed by Arcanemagus** 2019-12-23 20:12 UTC
