### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by hoangjoker** [AtomLinter/linter-gcc#210] opened 2019-12-24 07:42 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Kali GNU/Linux
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1
**User**: root

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /root/.atom/packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.1 
gpp-compiler 3.0.7 
linter-gcc 0.7.1 
switch-header-source 0.34.1 
```

**Comment by Arcanemagus** [comment] 2019-12-27 19:53
Duplicate of #209

**Closed by Arcanemagus** 2019-12-27 19:53 UTC
