### ISSUE TITLE
linter-gcc doesn't work

### ISSUE THREAD

**Issue by montecarloo** [AtomLinter/linter-gcc#206] opened 2019-07-02 06:39 UTC
## Checklist
gcc version:
> gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

installed packages:
- linter 2.3.0
- linter-gcc 0.7.1
- linter-ui-default 1.7.1
- busy-signal 2.0.1
- intentions 1.1.5

output of " /usr/bin/gcc -c -Wall -fmax-errors=0 Documents/cf/main.cpp " in terminal :

> Documents/cf/main.cpp: In function ‘int main()’:
Documents/cf/main.cpp:57:5: error: expected ‘;’ before ‘cout’
     cout<<n<<endl;
     ^~~~

**Comment by Delran** [comment] 2019-07-02 11:48
No, it doesn't, [linter-gcc2](https://atom.io/packages/linter-gcc2)

**Comment by montecarloo** [comment] 2019-07-02 11:55
linter-gcc2's lint-on-fly doesn't work to!

**Comment by Delran** [comment] 2019-10-29 13:14
Well, probably useless to answer now, but looks like you're trying to specify the path of your GCC executable without specifying that it is indeed an executable, you should either add GCC's bin folder in your PATH or write "/usr/bin/gcc.exe" in your linter settings.
Also it looks like you're trying to compile CPP code with GCC's C compiler wich is bound to fail, use g++.exe instead of gcc.exe.

**Comment by Arcanemagus** [comment] 2019-12-23 20:16
Duplicate of #199

**Closed by Arcanemagus** 2019-12-23 20:16 UTC
