### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by hoangjoker** [AtomLinter/linter-gcc#211] opened 2019-12-24 09:06 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Kali GNU/Linux
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1
**User**: root

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /root/.atom/packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
     -9:33.1.0 gpp-compiler:compile (div.line)
 22x -2:58.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.1.3 
busy-signal 2.0.1 
gpp 0.4.3 
linter-gcc 0.7.1 
```

**Comment by Arcanemagus** [comment] 2019-12-27 19:54
Duplicate of #209

**Closed by Arcanemagus** 2019-12-27 19:54 UTC
Labels: duplicate
