### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by digvijaysingh13** [AtomLinter/linter-gcc#214] opened 2019-12-25 16:00 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.3
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /home/optimus/.atom/packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
linter-gcc 0.7.1 
```

**Comment by Arcanemagus** [comment] 2019-12-27 19:54
Duplicate of #209

**Closed by Arcanemagus** 2019-12-27 19:54 UTC
Labels: duplicate
