### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by parthvyas7** [AtomLinter/linter-gcc#202] opened 2019-02-14 15:15 UTC
## Checklist
* [ ] Check that you have the GNU C Compiler installed by typing ```gcc --version``` into a terminal.
* [ ] If you don't have the ```linter``` package installed, either update to the latest version of ```linter-gcc``` or install linter directly with ```apm install linter```.
* [ ] Ensure that you are using a valid grammar - either C/C++/C++14
* [ ] Ensure that you have read all the relevant information in the [wiki](https://github.com/hebaishi/linter-gcc/wiki), particularly the [Common Issues](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues) page.

**Comment by therealadityashankar** [comment] 2019-10-27 14:21
I've caught the same issue
gcc version: 8.3.0

**Comment by Yundin** [comment] 2019-11-10 10:25
`brew install gcc` fixes this on mac

**Comment by Arcanemagus** [comment] 2019-12-23 19:31
Closing this as a duplicate of #209, simply as a place to gather the various reports of this issue together.

**Comment by Arcanemagus** [comment] 2019-12-23 19:31
Duplicate of #209

**Closed by Arcanemagus** 2019-12-23 19:31 UTC
