### ISSUE TITLE
atom-ide-diagnostics compatibility

### ISSUE THREAD

**Issue by SmiVan** [AtomLinter/linter-gcc#189] opened 2018-10-17 18:06 UTC
linter-gcc 0.7.1 seems to be incompatible with [atom-ide-diagnostics](https://github.com/facebook-atom/atom-ide-ui/tree/master/modules/atom-ide-ui/pkg/atom-ide-diagnostics).

I'm uncertain as to what the issue is, but this is the only linter package I know of that requires explicitly steelbrain's linter and doesn't work with [atom-ide](https://atom.io/packages/atom-ide-ui), which is unfortunate.

---

tvincent065's [extended-functionality](https://github.com/tvincent056/linter-gcc/tree/extended-functionality) pull request #185 implements this.

**Comment by Arcanemagus** [comment] 2019-12-23 20:12
Duplicate of #199

**Closed by Arcanemagus** 2019-12-23 20:12 UTC
