### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by Rontashvera** [AtomLinter/linter-gcc#208] opened 2019-12-23 10:11 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 19.10
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /home/sagebeast/.atom/packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
     -0:57.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
ide-c-cpp 0.1.0 
linter-gcc 0.7.1 
```

**Comment by Arcanemagus** [comment] 2019-12-23 19:32
Closing this as a duplicate of #209, simply as a place to gather the various reports of this issue together.

**Comment by Arcanemagus** [comment] 2019-12-23 19:32
Duplicate of #209

**Closed by Arcanemagus** 2019-12-23 19:32 UTC
