### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by Maxlanglet** [AtomLinter/linter-gcc#212] opened 2019-12-24 11:12 UTC
[Enter steps to reproduce:]

1. I simply dowloaded linter-gcc and this happened 

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /Users/langletmaxime/.atom/packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/linter-gcc/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
     -2:51 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
autocomplete-clang 0.12.1 
gpp-compiler 3.0.7 
linter-gcc 0.7.1 
minimap 4.29.9 
```

**Comment by Arcanemagus** [comment] 2019-12-27 19:54
Duplicate of #209

**Closed by Arcanemagus** 2019-12-27 19:54 UTC
Labels: duplicate
