### ISSUE TITLE
it stops working since the 1.34.0 atom update

### ISSUE THREAD

**Issue by SLICKIE** [AtomLinter/linter-gcc#204] opened 2019-03-28 04:39 UTC
## Checklist
* [ ] Check that you have the GNU C Compiler installed by typing ```gcc --version``` into a terminal.
* [ ] If you don't have the ```linter``` package installed, either update to the latest version of ```linter-gcc``` or install linter directly with ```apm install linter```.
* [ ] Ensure that you are using a valid grammar - either C/C++/C++14
* [ ] Ensure that you have read all the relevant information in the [wiki](https://github.com/hebaishi/linter-gcc/wiki), particularly the [Common Issues](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues) page.

**Comment by Delran** [comment] 2019-03-28 16:07
Actually it did stoped working since Linter 2.3.0 update, [LinterGCC2](https://github.com/tvincent056/linter-gcc2

**Comment by Arcanemagus** [comment] 2019-12-23 20:15
Duplicate of #199

**Closed by Arcanemagus** 2019-12-23 20:15 UTC
